### ISSUE TITLE
xReg: Use of "epoch" to mean "version" in xReg

### ISSUE THREAD

**Issue by duglin** [xregistry/spec#9]
@jskeet wrote:
The Discovery spec uses the "epoch" attribute as a form of version, and I don't currently understand the choice of term. I'd normally expect an epoch to be a sort of "reference point" from which other values are computed, e.g. timestamps being represented as "a number of seconds since the Unix epoch".

Is the Discovery use of the term epoch one which is common in other protocols?

Moved from: https://github.com/cloudevents/spec/issues/913

**Comment by duglin** [comment]
@jskeet do you have a recommendation for another term? `version` isn't a great choice since we have an entity called "version" and it could cause confusion.

**Comment by jskeet** [comment]
It doesn't look like epoch is used now - are you using version now, but wanting to move away from it?

**Comment by duglin** [comment]
We're still using `epoch`, see: https://github.com/xregistry/spec/blob/main/core/spec.md#epoch

**Comment by jskeet** [comment]
Okay, github search fail on my part apparently then :)

Okay, so this is a bit like version, but guaranteed to be monotonically increasing rather than user-specified, and guaranteed to be unique for the resource (you can potentially change the resource without changing the version, but you can't do that for the epoch). Is that about right?

I'm tempted to call it *something* with version in, e.g. uniqueversion, monotonicversion, metaversion, versioncounter. That at least means a reader has a better clue that it's tightly tied to versioning.

But if everyone else is happy with epoch, I don't want to rock the boat :)

**Comment by duglin** [comment]
> Okay, so this is a bit like version, but guaranteed to be monotonically increasing rather than user-specified, and guaranteed to be unique for the resource (you can potentially change the resource without changing the version, but you can't do that for the epoch). Is that about right?

correct. It serves a similar purpose as etag in http

My concern with the word "version" is that we have a "version" entity and I think there's a large possibility of people trying to make a correlation between the two. E.g. what's a Resources "unique version" vs it's "default version" ?

"counter", all by itself, isn't bad

**Comment by duglin** [comment]
on the 5/17 call we agreed to stick with "epoch" - will add something the primer to explain a bit about why
